name: carbon-driver-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - gpytorch
  - botorch
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - openpyxl
  - pip
  - pip:
      - tqdm
      - pytest
      - jupyter
      - seaborn
      - xlrd
      - xlsxwriter

